#
# Redis Dockerfile
#
# https://github.com/dockerfile/redis
#

# Pull base image.
FROM redis


# Maintainer
LABEL maintainer="Michael Ryan <mtritconsulting@outlook.com>"

# Copy Content to the /data/redis directory.
COPY ./data/*.data ./redis/
COPY ./data/loaddata.sh ./redis/

# Commands - load the data into redis.
RUN \
#  apt-get update && apt-get upgrade -y && \
  pwd && \
  cd /data/redis && \
  chmod +x loaddata.sh && \
  pwd && \
  ls -lta && \
  ls -lta loaddata.sh && \
  redis-server --daemonize yes && \
  bash -c echo '/usr/local/bin/redis-cli ping' && \
  /usr/local/bin/redis-cli ping && \
  bash -c echo 'Loading data...' && \
#  ./data/redis/loaddata.sh
  /usr/local/bin/redis-cli flushall async && \
  echo ">> Loading State Airports..." && \
  cat /data/redis/StateAirportsSetReady.data | /usr/local/bin/redis-cli --pipe  && \
  echo ">> Loading States..." && \
  cat /data/redis/StatesReady.data | /usr/local/bin/redis-cli --pipe && \
  echo ">> Loading Tasks..." && \
  cat /data/redis/TaskReady.data | /usr/local/bin/redis-cli --pipe && \
  echo ">> Loading GEO data..." && \
  cat /data/redis/GEOAirportDataReady.data | /usr/local/bin/redis-cli --pipe && \
  echo ">> Loading Call Log..." && \
  cat /data/redis/CallReady.data | /usr/local/bin/redis-cli --pipe

# Users

# Define mountable directories.

# Define working directory.

# Define default command.

# Expose ports.
