#
# Redis Dockerfile
#
# https://github.com/dockerfile/redis
#

# Pull base image.
FROM redis


# Maintainer
LABEL maintainer="MICHAEL Ryan <mtritconsulting@outlook.com>"

# Commands.
RUN cd /tmp

# Copy Content to the /data/redis directory.
COPY ./data/*.data ./redis/
COPY ./data/LoadData.sh ./redis/

# Users

# Define mountable directories.

# Define working directory.

# Define default command.

# Expose ports.
