#
# Redis Dockerfile
#
# https://github.com/dockerfile/redis
#

# Pull base image.
FROM redis


# Maintainer
LABEL maintainer="MICHAEL Ryan <mtritconsulting@outlook.com>"

# Copy Content to the /data/redis directory.
COPY ./data/*.data ./redis/
COPY ./data/loaddata.sh ./redis/

# Commands - load the data into redis.
RUN \
  pwd && \
  cd /data/redis && \
  chmod +x loaddata.sh && \
  pwd && \
  ls -lta && \
  ls -lta loaddata.sh
#  /usr/local/bin/redis-cli ping
#  ./loaddata.sh

# Users

# Define mountable directories.

# Define working directory.

# Define default command.

# Expose ports.
